# NLP with Machine Learning Assignment

1. Create a new _nlp_machine_learning_ environment
2. Launch Jupyter Notebook
3. Read in the _movie_reviews.csv_ file
4. Apply sentiment analysis to the _movie_info_ column
5. Sort the sentiment scores to return the top 10 and bottom 10 sentiment scores and their corresponding movie titles

In [39]:
import pandas as pd

pd.set_option('display.max_colwidth', None)
data_df = pd.read_csv("movie_reviews.csv")
data_df.head(2)

,movie_title,rating,genre,in_theaters_date,movie_info,directors,director_gender,tomatometer_rating,audience_rating,critics_consensus
0,A Dog's Journey,PG,"Drama, Kids & Family",5/17/19,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",Gail Mancuso,female,50,92,"A Dog's Journey is as sentimental as one might expect, but even cynical viewers may find their ability to resist shedding a tear stretched to the puppermost limit."
1,A Dog's Way Home,PG,Drama,1/11/19,"Separated from her owner, a dog sets off on an 400-mile journey to get back to the safety and security of the place she calls home. Along the way, she meets a series of new friends and manages to bring a little bit of comfort and joy to their lives.",Charles Martin Smith,male,60,71,"A Dog's Way Home may not quite be a family-friendly animal drama fan's best friend, but this canine adventure is no less heartwarming for its familiarity."

In [40]:
df = data_df.copy()

In [41]:
phrase = df['movie_info'][0]
phrase

'Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his "boy," Ethan (Dennis Quaid) and Ethan\'s wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah\'s baby granddaughter, CJ. The problem is that CJ\'s mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey\'s soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey\'s adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ\'s best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.'

In [42]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()
sentiment = analyzer.polarity_scores(phrase)
sentiment

{'neg': 0.051, 'neu': 0.694, 'pos': 0.255, 'compound': 0.9837}

In [43]:
# define a function to classify the sentiment based on the compound score
def sentiment_score(text):
    analyzer = SentimentIntensityAnalyzer()
    return analyzer.polarity_scores(text)['compound']

In [44]:
df['sentiment_score'] = df['movie_info'].apply(sentiment_score)

In [45]:
df.head(2)

,movie_title,rating,genre,in_theaters_date,movie_info,directors,director_gender,tomatometer_rating,audience_rating,critics_consensus,sentiment_score
0,A Dog's Journey,PG,"Drama, Kids & Family",5/17/19,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",Gail Mancuso,female,50,92,"A Dog's Journey is as sentimental as one might expect, but even cynical viewers may find their ability to resist shedding a tear stretched to the puppermost limit.",0.9837
1,A Dog's Way Home,PG,Drama,1/11/19,"Separated from her owner, a dog sets off on an 400-mile journey to get back to the safety and security of the place she calls home. Along the way, she meets a series of new friends and manages to bring a little bit of comfort and joy to their lives.",Charles Martin Smith,male,60,71,"A Dog's Way Home may not quite be a family-friendly animal drama fan's best friend, but this canine adventure is no less heartwarming for its familiarity.",0.9237

In [50]:
top_10_sentiment = df[['movie_title','movie_info','sentiment_score']].sort_values(by='sentiment_score', ascending=False).head(10)
top_10_sentiment

,movie_title,movie_info,sentiment_score
23,Breakthrough,"BREAKTHROUGH is based on the inspirational true story of one mother's unfaltering love in the face of impossible odds. When Joyce Smith's adopted son John falls through an icy Missouri lake, all hope seems lost. But as John lies lifeless, Joyce refuses to give up. Her steadfast belief inspires those around her to continue to pray for John's recovery, even in the face of every case history and scientific prediction. From producer DeVon Franklin (Miracles from Heaven) and adapted for the screen by Grant Nieporte (Seven Pounds) from Joyce Smith's own book, BREAKTHROUGH is an enthralling reminder that faith and love can create a mountain of hope, and sometimes even a miracle.",0.9915
81,Missing Link,"This April, meet Mr. Link (Galifianakis): 8 feet tall, 630 lbs, and covered in fur, but don't let his appearance fool you... he is funny, sweet, and adorably literal, making him the world's most lovable legend at the heart of Missing Link, the globe-trotting family adventure from LAIKA. Tired of living a solitary life in the Pacific Northwest, Mr. Link recruits fearless explorer Sir Lionel Frost (Jackman) to guide him on a journey to find his long-lost relatives in the fabled valley of Shangri-La. Along with adventurer Adelina Fortnight (Saldana), our fearless trio of explorers encounter more than their fair share of peril as they travel to the far reaches of the world to help their new friend. Through it all, the three learn that sometimes you can find a family in the places you least expect.",0.9909
130,The Laundromat,"When her idyllic vacation takes an unthinkable turn, Ellen Martin (Academy Award winner Meryl Streep) begins investigating a fake insurance policy, only to find herself down a rabbit hole of questionable dealings that can be linked to a Panama City law firm and its vested interest in helping the world's wealthiest citizens amass even larger fortunes. The charming -- and very well-dressed -- founding partners Jürgen Mossack (Academy Award winner Gary Oldman) and Ramón Fonseca (Golden Globe nominee Antonio Banderas) are experts in the seductive ways shell companies and offshore accounts help the rich and powerful prosper. They are about to show us that Ellen's predicament only hints at the tax evasion, bribery and other illicit absurdities that the super wealthy indulge in to support the world's corrupt financial system.",0.9908
48,Five Feet Apart,"Stella Grant (Haley Lu Richardson) is every bit a seventeen-year-old... she's attached to her laptop and loves her best friends. But unlike most teenagers, she spends much of her time living in a hospital as a cystic fibrosis patient. Her life is full of routines, boundaries and self-control -- all of which is put to the test when she meets an impossibly charming fellow CF patient named Will Newman (Cole Sprouse). There's an instant flirtation, though restrictions dictate that they must maintain a safe distance between them. As their connection intensifies, so does the temptation to throw the rules out the window and embrace that attraction. Further complicating matters is Will's potentially dangerous rebellion against his ongoing medical treatment. Stella gradually inspires Will to live life to the fullest, but can she ultimately save the person she loves when even a single touch is off limits?",0.9889
156,UglyDolls,"In the adorably different town of Uglyville, weird is celebrated, strange is special and beauty is embraced as more than simply meets the eye. Here, the free-spirited Moxy (Clarkson) and her UglyDoll friends live every day in a whirlwind of bliss, letting their freak flags fly in a celebration of life and its endless possibilities. In this all-new story, the UglyDolls will go on a journey beyond the comfortable borders of Uglyville. There, they will confront what it means to be different, struggle with their desire to be loved, and ultimately discover that you don't have to be perfect to be amazing because who you truly are is what matters most.",0.9862
93,Red Joan,"In a picturesque village in England, Joan Stanley (Academy Award (R) winner Dame Judi Dench), lives in contented retirement. Then suddenly her tranquil existence is shattered as she's shockingly arrested by MI5. For Joan has been hiding an incredible past; she is one of the most influential spies in living history... Cambridge University in the 1930s, and the young Joan (Sophie Cookson), a demure physics student, falls intensely in love with a seductively attractive Russian saboteur, Leo. Through him, she begins to see that the world is on a knife-edge and perhaps must be saved from itself in the race to military supremacy. Post-war and now working at a top secret nuclear research facility, Joan is confronted with the impossible: Would you betray your country and your loved ones, if it meant saving them? What price would you pay for peace? Inspired by an extraordinary true story, Red Joan is the taut and emotional discovery of one woman's sacrifice in the face of incredible circumstances. A woman to whom we perhaps all owe our freedom.",0.9848
49,Giant Little Ones,"Franky Winter (Josh Wiggins) and Ballas Kohl (Darren Mann) have been best friends since childhood. They are high school royalty: handsome, stars of the swim team and popular with girls. They live a perfect teenage life - until the night of Franky's epic 17th birthday party, when Franky and Ballas are involved in an unexpected incident that changes their lives forever. Giant Little Ones is a heartfelt and intimate coming-of-age story about friendship, self-discovery, and the power of love without labels.",0.9839
0,A Dog's Journey,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",0.9837
36,Dumbo,"From Disney and visionary director Tim Burton, the all-new grand live-action adventure ""Dumbo"" expands on the beloved classic story where differences are celebrated, family is cherished and dreams take flight. Circus owner Max Medici (Danny DeVito) enlists former star Holt Farrier (Colin Farrell) and his children Milly (Nico Parker) and Joe (Finley Hobbins) to care for a newborn elephant whose oversized ears make him a laughingstock in an already struggling circus. But when they discover that Dumbo can fly, the circus makes an incredible comeback, attracting persuasive entrepreneur V.A. Vandevere (Michael Keaton), who recruits the peculiar pachyderm for his newest, larger-than-life entertainment venture, Dreamland. Dumbo soars to new heights alongside a charming and spectacular aerial artist, Colette Marchant (Eva Green), until Holt learns that beneath its shiny veneer, Dreamland is full of dark secrets.",0.9801
71,Long Shot,"Fred Flarsky (Seth Rogen) is a gifted and free-spirited journalist with an affinity for trouble. Charlotte Field (Charlize Theron) is one of the most influential women in the world. Smart, sophisticated, and accomplished, she's a powerhouse diplomat with a talent for... well, mostly everything. The two have nothing in common, except that she was his babysitter and childhood crush. When Fred unexpectedly reconnects with Charlotte, he charms her with his self-deprecating humor and his memories of her youthful idealism. As she prepares to make a run for the Presidency, Charlotte impulsively hires Fred as her speechwriter, much to the dismay of her trusted advisors. A fish out of water on Charlotte's elite team, Fred is unprepared for her glamorous lifestyle in the limelight. However, sparks fly as their unmistakable chemistry leads to a round-the-world romance and a series of unexpected and dangerous incidents.",0.9778

In [51]:
btn_10_sentiment = df[['movie_title','movie_info','sentiment_score']].sort_values(by='sentiment_score', ascending=False).tail(10)
btn_10_sentiment

,movie_title,movie_info,sentiment_score
40,El Chicano,"When L.A.P.D. Detective Diego Hernandez is assigned a career-making case investigating a vicious cartel, he uncovers links to his brother's supposed suicide and a turf battle that's about to swallow his neighborhood. Torn between playing by the book and seeking justice, he resurrects the masked street legend El Chicano. Now, out to take down his childhood buddy turned gang boss, he sets off a bloody war to defend his city and avenge his brother's murder",-0.9578
142,The Standoff at Sparrow Creek,"After a mass shooting at a police funeral, reclusive ex-cop Gannon finds himself unwittingly forced out of retirement when he realizes that the killer belongs to the same militia he joined after quitting the force. Understanding that the shooting could set off a chain reaction of copycat violence across the country, Gannon quarantines his fellow militiamen in the remote lumber mill they call their headquarters. There, he sets about a series of grueling interrogations, intent on ferreting out the killer and turning him over to the authorities to prevent further bloodshed.",-0.9590
87,Pet Sematary,"Based on the seminal horror novel by Stephen King, Pet Sematary follows Dr. Louis Creed (Jason Clarke), who, after relocating with his wife Rachel (Amy Seimetz) and their two young children from Boston to rural Maine, discovers a mysterious burial ground hidden deep in the woods near the family's new home. When tragedy strikes, Louis turns to his unusual neighbor, Jud Crandall (John Lithgow), setting off a perilous chain reaction that unleashes an unfathomable evil with horrific consequences.",-0.9590
113,The Curse of La Llorona,"In 1970s Los Angeles, La Llorona is stalking the night -- and the children. Ignoring the eerie warning of a troubled mother suspected of child endangerment, a social worker and her own small kids are soon drawn into a frightening supernatural realm. Their only hope to survive La Llorona's deadly wrath may be a disillusioned priest and the mysticism he practices to keep evil at bay, on the fringes where fear and faith collide.",-0.9628
27,Charlie Says,"Three young women were sentenced to death for the infamous Manson murders. Their sentences became life imprisonment when the death penalty was lifted in California. One young graduate student was sent in to teach them. Through her, we witness their transformations as they face the reality of their horrific crimes.",-0.9643
11,Angel of Mine,"Noomi Rapace (The Girl with the Dragon Tattoo) stars as a woman on the edge in this intense psychological thriller. Having suffered a tragic loss years earlier, Lizzie (Rapace) is trying to rebuild her life when she suddenly becomes obsessed with a neighbor's daughter, believing the girl to be her own child. As Lizzie's shocking, threatening acts grow increasingly dangerous, they lead to an explosive confrontation with the girl's angry, defensive mother (Yvonne Strahovski, ""The Handmaid's Tale"").",-0.9687
154,Triple Threat,"TRIPLE THREAT, the newest feature from Johnson, is an adrenaline fueled and gritty action thriller starring some of the biggest names in action today. Michael Jai White (BLACK DYNAMITE; UNDISPUTED 2: LAST MAN STANDING), Scott Adkins (Marvel's DOCTOR STRANGE; THE EXPENDABLES 2), Michael Bisping (xXx: RETURN OF XANDER CAGE) star as a group of professional assassins hired to take out a billionaire's daughter who is intent on bringing down a major crime syndicate. A down and out team of mercenaries, played by Tony Jaa (ONG BAK TRILOGY; xXx: RETURN OF XANDER CAGE), Iko Uwais (THE RAID 1 & 2; STAR WARS: THE FORCE AWAKENS) and Tiger Chen (MAN OF TAI CHI), must take on the assassins and stop them before they kill their target. The film co-stars JeeJa Yanin (CHOCOLATE) Michael Wong (Cold War) and Celina Jade (WOLF WARRIOR 2).",-0.9696
83,Nightmare Cinema,"In this twisted horror anthology, five strangers are drawn to an abandoned theater and forced to watch their deepest and darkest fears play out before them. Lurking in the shadows is the Projectionist, who preys upon their souls with his collection of disturbing films. As each reel spins its sinister tale, the characters find frightening parallels to their own lives.",-0.9756
148,The Wind,"An unseen evil haunts the homestead in this chilling, folkloric tale of madness, paranoia, and otherworldly terror. Lizzy (Caitlin Gerard) is a tough, resourceful frontierswoman settling a remote stretch of land on the 19th-century American frontier. Isolated from civilization in a desolate wilderness where the wind never stops howling, she begins to sense a sinister presence that seems to be borne of the land itself, an overwhelming dread that her husband (Ashley Zukerman) dismisses as superstition. When a newlywed couple arrives on a nearby homestead, their presence amplifies Lizzy's fears, setting into motion a shocking chain of events. Masterfully blending haunting visuals with pulse-pounding sound design, director Emma Tammi evokes a godforsaken world in which the forces of nature come alive with quivering menace.",-0.9838
7,All Is True,"The year is 1613, Shakespeare is acknowledged as the greatest writer of the age. But disaster strikes when his renowned Globe Theatre burns to the ground, and devastated, Shakespeare returns to Stratford, where he must face a troubled past and a neglected family. Haunted by the death of his only son Hamnet, he struggles to mend the broken relationships with his wife and daughters. In so doing, he is ruthlessly forced to examine his own failings as husband and father. His very personal search for the truth uncovers secrets and lies within a family at war.",-0.9955

# Text Clasification

1. Clean and normalize the _movie_info_ column using the _maven_text_preprocessing.py_ module
2. Create a Count Vectorizer
* Remove stop words
* Set the minimum document frequency to 10%
3. Create a Naïve Bayes model and a Logistic Regression model to predict which movies are directed by women vs men using the CV
4. Compare their accuracy scores and classification reports
5. Using the better performing model, return the top 5 movies that the model predicts are most likely directed by a women

In [59]:
# Training model
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [ ]:
df['director_gender'].value_counts()
# df['director_gender'].value_counts(normalize=True)*100 in percentage

director_gender
male      134
female     32
Name: count, dtype: int64

In [55]:
import text_preprocessing as tp

In [123]:
df['clean_movie_info'] = tp.nlp_pipeline(df['movie_info'])

In [124]:
df[['movie_info','clean_movie_info']].head(2)

,movie_info,clean_movie_info
0,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",bailey voice josh gad live good life michigan farm boy ethan dennis quaid ethans wife hannah marg helgenberger new playmate ethan hannah baby granddaughter cj problem cjs mom gloria betty gilpin decide cj away bailey soul prepare leave life new make promise ethan find cj protect cost begin bailey adventure multiple life fill love friendship devotion cj kathryn prescott cjs good friend trent henry lau experience joy heartbreak music laughter good belly rub
1,"Separated from her owner, a dog sets off on an 400-mile journey to get back to the safety and security of the place she calls home. Along the way, she meets a series of new friends and manages to bring a little bit of comfort and joy to their lives.",separate owner dog set 400mile journey safety security place call home way meet series new friend manage bring little bit comfort joy life

In [ ]:
# Count Vectorizer
vectorizer = CountVectorizer(stop_words="english", min_df=.10)
X = vectorizer.fit_transform(df.clean_movie_info)
X_df = pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names_out())


# TF-IDF Vectorizer
tfidf = TfidfVectorizer(stop_words="english", min_df=.10)
Xt = tfidf.fit_transform(df.clean_movie_info)
Xt_df = pd.DataFrame(Xt.toarray(),columns=tfidf.get_feature_names_out())

,begin,discover,family,film,follow,force,friend,home,leave,life,live,love,man,new,set,star,story,turn,woman,world,year,young
0,0.282820,0.000000,0.0,0.000000,0.000000,0.0,0.244936,0.000000,0.296518,0.635681,0.28282,0.278667,0.0,0.458654,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000
1,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.437857,0.491047,0.000000,0.378789,0.00000,0.000000,0.0,0.409954,0.505580,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000
2,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,1.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000
3,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.0,1.000000,0.000000,0.0,0.000000
4,0.000000,0.000000,0.0,0.000000,0.675662,0.0,0.000000,0.000000,0.000000,0.513763,0.00000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.528705,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.791943,0.00000,0.000000,0.0,0.000000,0.610595,0.0,0.000000
162,0.000000,0.000000,0.0,0.521979,0.529535,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.00000,0.449990,0.0,0.494610,0.000000,0.0,0.000000
163,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.55909,0.446502,0.0,0.490777,0.000000,0.0,0.497184
164,0.559761,0.000000,0.0,0.000000,0.000000,0.0,0.484780,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.515164,0.431580,0.0,0.000000
165,0.000000,0.760834,0.0,0.000000,0.000000,0.0,0.648946,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000

In [ ]:
#CountVectorizer
X_df.head()

,begin,discover,family,film,follow,force,friend,home,leave,life,live,love,man,new,set,star,story,turn,woman,world,year,young
0,1,0,0,0,0,0,1,0,1,3,1,1,0,2,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,1,1,0,1,0,0,0,1,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0

In [80]:
#TF-IDF Vectorizer
Xt_df.head()

,begin,discover,family,film,follow,force,friend,home,leave,life,live,love,man,new,set,star,story,turn,woman,world,year,young
0,0.28282,0.0,0.0,0.0,0.000000,0.0,0.244936,0.000000,0.296518,0.635681,0.28282,0.278667,0.0,0.458654,0.00000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
1,0.00000,0.0,0.0,0.0,0.000000,0.0,0.437857,0.491047,0.000000,0.378789,0.00000,0.000000,0.0,0.409954,0.50558,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
2,0.00000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,1.000000,0.00000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
3,0.00000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,1.0,0.000000,0.0,0.0
4,0.00000,0.0,0.0,0.0,0.675662,0.0,0.000000,0.000000,0.000000,0.513763,0.00000,0.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.528705,0.0,0.0

In [81]:
y = df.director_gender ## use with CountVectorizer
yt = df.director_gender ## Use with TF-IDF Vectorizer
y.head(2)

0    female
1      male
Name: director_gender, dtype: str

In [86]:
# ---------------------------------------------------
# Count Vectorizer Train-Test Split
# ---------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_df,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
# ---------------------------------------------------
# TF-IDF Vectorizer Train-Test Split
# ---------------------------------------------------
Xt_train, Xt_test, yt_train, yt_test = train_test_split(
    Xt_df,
    yt,
    test_size=0.2,
    random_state=42,
    stratify=y
)
X_train.shape, Xt_train.shape

((132, 22), (132, 22))

# Model Comparison for Count Vectorizer

In [88]:
# ---------------------------------------------------
# Train
# ---------------------------------------------------
nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)

MultinomialNB()

In [89]:
# ---------------------------------------------------
# Train
# ---------------------------------------------------
model_lr = LogisticRegression()
model_lr.fit(X_train, y_train)

LogisticRegression()

In [90]:
# ---------------------------------------------------
# Prediction
# ---------------------------------------------------
y_pred_nb = nb_model.predict(X_test)
# ---------------------------------------------------
# Prediction
# ---------------------------------------------------
y_pred_lr = model_lr.predict(X_test)

In [97]:
# ---------------------------------------------------
# Evaluation NB
# ---------------------------------------------------
print("\nClassification Report")
print(classification_report(y_test, y_pred_nb))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_nb))

print("Accuracy:", accuracy_score(y_test, y_pred_nb),"\n")

print("<<<<<<<<<<<<<<<<<<<<<<<<<<<<Below Is for LOgistic Regression>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
# ---------------------------------------------------
# Evaluation LR
# ---------------------------------------------------
print("\nClassification Report LR")
print(classification_report(y_test, y_pred_lr))

print("\nConfusion Matrix LR")
print(confusion_matrix(y_test, y_pred_lr))

print("Accuracy LR:", accuracy_score(y_test, y_pred_lr))

Classification Report
              precision    recall  f1-score   support

      female       1.00      0.14      0.25         7
        male       0.82      1.00      0.90        27

    accuracy                           0.82        34
   macro avg       0.91      0.57      0.57        34
weighted avg       0.86      0.82      0.77        34


Confusion Matrix
[[ 1  6]
 [ 0 27]]
Accuracy: 0.8235294117647058

<<<<<<<<<<<<<<<<<<<<<<<<<<<<Below Is for LOgistic Regression>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Classification Report LR
              precision    recall  f1-score   support

      female       0.50      0.14      0.22         7
        male       0.81      0.96      0.88        27

    accuracy                           0.79        34
   macro avg       0.66      0.55      0.55        34
weighted avg       0.75      0.79      0.75        34


Confusion Matrix LR
[[ 1  6]
 [ 1 26]]
Accuracy LR: 0.7941176470588235

In [126]:
df['Female_Predicted_nb'] = nb_model.predict_proba(X_df)[:,0]
df['Female_Predicted_lr'] = model_lr.predict_proba(X_df)[:,0]

(df[['director_gender','sentiment_score',
     'Female_Predicted_nb','Female_Predicted_lr']].sort_values(by="Female_Predicted_nb", 
                                                 ascending=False).head(10))

   director_gender  sentiment_score  Female_Predicted_nb  Female_Predicted_lr
38          female           0.4497             0.795158             0.708748
97          female           0.7217             0.763742             0.686845
27          female          -0.9643             0.756232             0.652506
55            male           0.9042             0.733803             0.721414
85          female           0.9259             0.631434             0.616405
0           female           0.9837             0.614525             0.498138
70          female          -0.8485             0.602896             0.496521
98            male           0.9100             0.571426             0.428178
69          female           0.7794             0.484770             0.503580
93            male           0.9848             0.475001             0.435501

In [240]:
df.columns

Index(['movie_title', 'rating', 'genre', 'in_theaters_date', 'movie_info',
       'directors', 'director_gender', 'tomatometer_rating', 'audience_rating',
       'critics_consensus', 'sentiment_score', 'clean_movie_info',
       'Female_Predicted_nb', 'Female_Predicted_lr'],
      dtype='str')

In [307]:
df_sort = df[['movie_title','director_gender','sentiment_score','Female_Predicted_nb','movie_info']]

# Topic Modelling Assignment

1. Using the same preprocessed data as the last assignment, create a Tfidf Vectorizer
* Remove stop words
* Start with min_df = 0.05 and max_df=0.2
2. Create an NMF model to find the main topics in the movie descriptions
* Start with n_components=2
3. Tweak the model by updating the Tfidf Vectorizer parameters and number of topics
4. Interpret and name the topics
5. For two of the topics, return the top movies that contain the topic

In [308]:
# TF-IDF Vectorizer
tfidf1 = TfidfVectorizer(stop_words="english", min_df=0.05, max_df=0.2)
Xt1 = tfidf1.fit_transform(df.clean_movie_info)
Xt_df1 = pd.DataFrame(Xt1.toarray(),columns=tfidf1.get_feature_names_out())

In [309]:
Xt_df1

,academy,action,adventure,american,base,battle,begin,black,bring,change,child,city,come,comedy,dark,daughter,day,deadly,director,discover,dream,event,evil,face,fall,family,father,fear,fight,film,follow,force,friend,future,girl,good,grow,help,hero,home,hope,husband,include,increasingly,inspire,john,join,journey,lead,leave,live,love,make,man,meet,mother,mysterious,night,past,play,power,return,run,save,school,search,secret,series,set,son,star,struggle,survive,think,thriller,time,town,true,try,turn,unexpected,war,way,woman,work,year,young
0,0.0,0.0,0.264584,0.0,0.000000,0.0,0.234867,0.0,0.00000,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.203406,0.000000,0.0,0.764617,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.246242,0.234867,0.231418,0.281898,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.00000
1,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.37314,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.275308,0.000000,0.0,0.000000,0.0,0.0,0.0,0.308752,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.358112,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.400694,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.400694,0.317890,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.37314,0.000000,0.0,0.0,0.00000
2,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.529071,0.0,0.0,0.000000,0.0,0.0,0.585172,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.614538,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.00000
3,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.441071,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.493518,0.0,0.0,0.469935,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.459581,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.00000,0.360338,0.0,0.0,0.00000
4,0.0,0.0,0.000000,0.0,0.309702,0.0,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.0,0.000000,0.33117,0.309702,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.265508,0.0,0.000000,0.339655,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.323424,0.0,0.339655,0.00000,0.303560,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.309702,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.323424,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.648502,0.0,0.000000,0.000000,0.0,0.000000,0.761213,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.00000
162,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.0,0.394824,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.333654,0.338484,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.412319,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.422194,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.412319,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.00000,0.316159,0.0,0.0,0.00000
163,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.00000,0.0,0.496528,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.47747,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.452943,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.00000,0.397599,0.0,0.0,0.40279
164,0.0,0.0,0.000000,0.0,0.000000,0.0,0.431795,0.0,0.00000,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.373955,0.544268,0.0,0.468574,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.00000,0.397393,0.0,0.0,0.00000
165,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.346582,0.370411,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.295614,0.000000,0.0,0.370411,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00000,0.384525,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.430247,0.0,0.000000,0.000000,0.0,0.430247,0.0,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.00000

In [310]:
Xt_df1.shape

(166, 87)

In [311]:
from sklearn.decomposition import NMF

nmf = NMF(n_components=5, max_iter=500, random_state=42)
W = nmf.fit_transform(Xt_df1) # Documnets-Topics
H = nmf.components_ # Topics-Terms

In [312]:
H.shape

(5, 87)

In [313]:
# function to display the top terms for each topic
def display_topics(H, num_words=10):
    for topic_num, topic_array in enumerate(H):
        top_features = topic_array.argsort()[::-1][:num_words]
        top_words = [tfidf1.get_feature_names_out()[i] for i in top_features]
        print("Topic", topic_num+1, ":", ', '.join(top_words))

In [314]:
display_topics(H)

Topic 1 : family, day, father, discover, fight, war, journey, secret, past, lead
Topic 2 : set, force, turn, evil, follow, hero, night, join, bring, begin
Topic 3 : film, true, event, inspire, base, comedy, follow, come, year, director
Topic 4 : friend, good, dream, help, live, town, adventure, begin, leave, love
Topic 5 : woman, young, man, mother, star, thriller, face, child, think, deadly

In [315]:
topics = pd.DataFrame(W, columns=['Growth','Entertaiment','Action','Dramatic-Fiction','Family'])
topics.head()

     Growth  Entertaiment    Action  Dramatic-Fiction    Family
0  0.000000      0.000000  0.000000          0.398853  0.000000
1  0.047314      0.199409  0.000000          0.111780  0.000000
2  0.072599      0.000000  0.000000          0.109538  0.000000
3  0.000000      0.000000  0.078209          0.000000  0.295483
4  0.035667      0.021792  0.096731          0.103637  0.043054

In [316]:
print(topics.iloc[:, 1:].dtypes)

Entertaiment        float64
Action              float64
Dramatic-Fiction    float64
Family              float64
dtype: object

In [319]:
doc_topics = pd.concat([df_sort, topics], axis=1)
doc_topics.head(1)

,movie_title,director_gender,sentiment_score,Female_Predicted_nb,movie_info,Growth,Entertaiment,Action,Dramatic-Fiction,Family
0,A Dog's Journey,female,0.9837,0.614525,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",0.0,0.0,0.0,0.398853,0.0

In [ ]:
# in each row of topics that has highest value assigned its label to new Topic column as
doc_topics['Topics'] = doc_topics.iloc[:,5:].idxmax(axis=1)
doc_topics.head(1)

,movie_title,director_gender,sentiment_score,Female_Predicted_nb,movie_info,Growth,Entertaiment,Action,Dramatic-Fiction,Family,Topics
0,A Dog's Journey,female,0.9837,0.614525,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",0.0,0.0,0.0,0.398853,0.0,Dramatic-Fiction

In [ ]:
(doc_topics[['movie_title','movie_info','Growth',
             'Entertaiment','Action','Dramatic-Fiction',
             'Family','Topics']].sort_values(by='Family', ascending=False).head(5))

,movie_title,movie_info,Growth,Entertaiment,Action,Dramatic-Fiction,Family,Topics
163,Wild Rose,"WILD ROSE tells the complicated story of Rose-Lynn, a woman on a quest to become a country music star, while also grappling with the responsibilities of being recently released from prison and a young mother of two children.",0.000000,0.000000,0.000000,0.000000,0.469456,Family
27,Charlie Says,"Three young women were sentenced to death for the infamous Manson murders. Their sentences became life imprisonment when the death penalty was lifted in California. One young graduate student was sent in to teach them. Through her, we witness their transformations as they face the reality of their horrific crimes.",0.000000,0.000000,0.000000,0.000000,0.426485,Family
69,Little,"Marsai Martin (TV's Black-ish) stars in and executive produces Universal Pictures' LITTLE, a comedy from producer Will Packer (Girls Trip, Ride Along and Think Like a Man series) based on an idea the young actress pitched. Directed by Tina Gordon (Peeples), the film tells the story of a woman who-when the pressures of adulthood become too much to bear-gets the chance to relive the carefree life of her younger self.",0.000000,0.000000,0.173038,0.000000,0.381822,Family
97,Rust Creek,"An ordinary woman must summon extraordinary courage to survive a nightmare odyssey in this harrowing survival thriller. Sawyer (Hermione Corfield) is an ambitious, overachieving college senior with a seemingly bright future. While on her way to a job interview, a wrong turn leaves her stranded deep in the frozen Kentucky woods. Suddenly, the young woman with everything to live for finds herself facing her own mortality as she's punished by the elements and pursued by a band of ruthless outlaws. With nowhere left to run, she is forced into an uneasy alliance with Lowell (Jay Paulson), an enigmatic loner with shadowy intentions. Though she's not sure she can trust him, Sawyer must take a chance if she hopes to escape Rust Creek alive.",0.011951,0.081077,0.000000,0.078182,0.324233,Family
124,The Hustle,"Rebel Wilson and Anne Hathaway have winning chemistry as a pair of con artists plying their trade in a stunning seaside town in the south of France. Josephine Chesterfield (Hathaway) is a glamorous, seductive Brit with a sprawling home in Beaumont-sur-Mer and a penchant for defrauding gullible wealthy men from all corners of the world. Into her well-ordered, meticulously moneyed world bursts Penny Rust (Wilson), an Aussie who is as free-form and fun-loving as Josephine is calculated and cunning. Where Penny amasses wads of cash by ripping off her marks in neighborhood bars, Josephine fills her safe with massive diamonds after ensnaring her prey in glitzy casinos. Despite their different methods, both are masters of the art of the fleece so they con the men that have wronged women. Wilson's talent for physicality and Hathaway's withering wit are a combustible combination as the pair of scammers pull out all the stops to swindle a naïve tech billionaire (Alex Sharp).",0.000000,0.000000,0.000000,0.061003,0.315736,Family

In [326]:
(doc_topics[['movie_title','movie_info','Growth',
             'Entertaiment','Action','Dramatic-Fiction',
             'Family','Topics']].sort_values(by='Entertaiment', ascending=False).head(5))

,movie_title,movie_info,Growth,Entertaiment,Action,Dramatic-Fiction,Family,Topics
26,Captive State,"Set in a Chicago neighborhood nearly a decade after an occupation by an extra-terrestrial force, ""Captive State"" explores the lives on both sides of the conflict - the collaborators and dissidents.",0.000000,0.503831,0.000000,0.000000,0.000000,Entertaiment
142,The Standoff at Sparrow Creek,"After a mass shooting at a police funeral, reclusive ex-cop Gannon finds himself unwittingly forced out of retirement when he realizes that the killer belongs to the same militia he joined after quitting the force. Understanding that the shooting could set off a chain reaction of copycat violence across the country, Gannon quarantines his fellow militiamen in the remote lumber mill they call their headquarters. There, he sets about a series of grueling interrogations, intent on ferreting out the killer and turning him over to the authorities to prevent further bloodshed.",0.000000,0.502896,0.000000,0.000000,0.000000,Entertaiment
16,Ash Is Purest White,"A tragicomedy initially set in the jianghu-criminal underworld-setting, ASH IS PUREST WHITE is less a gangster movie than a melodrama. With a three-part structure, it begins by following the quick-witted Qiao (Tao Zhao) and her mobster boyfriend Bin (Fan Liao) as they stake out their turf against rivals and upstarts in 2001 postindustrial Datong before expanding out into an epic narrative of how abstract forces shape individual lives, and continues Jia Zhangke's body of work as a record of 21st-century China and its warp-speed transformations.",0.000000,0.396536,0.034004,0.006690,0.000000,Entertaiment
101,Shazam!,"We all have a superhero inside us, it just takes a bit of magic to bring it out. In Billy Batson's (Asher Angel) case, by shouting out one word--SHAZAM!--this streetwise 14-year-old foster kid can turn into the adult Super Hero Shazam (Zachary Levi), courtesy of an ancient wizard. Still a kid at heart--inside a ripped, godlike body--Shazam revels in this adult version of himself by doing what any teen would do with superpowers: have fun with them! Can he fly? Does he have X-ray vision? Can he shoot lightning out of his hands? Can he skip his social studies test? Shazam sets out to test the limits of his abilities with the joyful recklessness of a child. But he'll need to master these powers quickly in order to fight the deadly forces of evil controlled by Dr. Thaddeus Sivana (Strong).",0.007748,0.360994,0.000000,0.000000,0.049204,Entertaiment
144,The Unicorn,"When an engaged couple, Caleb (Nick Rutherford) and Malory (Lauren Lapkus), is forced to visit Palm Springs for a weekend to celebrate Malory's parents' 25th wedding vow renewal, they discover the apparent secret to their happy marriage. Determined to properly celebrate their own 're-engagement,' they set out on a wild night, but this fun and innocent new experience takes an intense turn, exposing deeper relationship problems and threatening their future together.",0.039484,0.347726,0.000000,0.016735,0.000000,Entertaiment

In [293]:
doc_topics.groupby('Topics')['sentiment_score'].mean()

Topics
Action                 0.243952
Dramatic-Fiction       0.689840
Entertaiment          -0.325190
Family                -0.286880
Female_Predicted_lr    0.036118
Growth                -0.097091
Name: sentiment_score, dtype: float64