In [1]:
# import libraries
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

In [4]:
from pathlib import Path
# Find the folder where your notebook is located
NOTEBOOK_DIR = Path.cwd()
# If using pathlib, construct the path dynamically
# If the "Data" folder is sitting inside "Course Materials" relative to the notebook:
# file_path = NOTEBOOK_DIR / "Course Materials" / "Data" / "Popchip.xlsx"
data_path = NOTEBOOK_DIR / "Course Materials" / "Data" / "Popchip_Reviews.xlsx"

# read in the pop chip reviews
reviews = pd.read_excel(data_path)
reviews.head(2)

,Id,UserId,Rating,Priority,Title,Text
0,23689,A21SYVGVNG8RAS,5,Low,Yummy snacks!,Popchips are the bomb!! I use the parmesan ga...
1,23690,AQJYXC0MPRQJL,5,Low,Great chip that is different from the rest,I like the puffed nature of this chip that mak...

In [9]:
import text_preprocessing as tp

reviews['Clean_Text'] = tp.nlp_pipeline(reviews.Text)
reviews.head(2)

,Id,UserId,Rating,Priority,Title,Text,Clean_Text
0,23689,A21SYVGVNG8RAS,5,Low,Yummy snacks!,Popchips are the bomb!! I use the parmesan ga...,popchip bomb use parmesan garlic scoop cotta...
1,23690,AQJYXC0MPRQJL,5,Low,Great chip that is different from the rest,I like the puffed nature of this chip that mak...,like puff nature chip make unique chip market ...

In [11]:
# create a count vectorizer matrix
cv = CountVectorizer(stop_words='english', ngram_range=(1,2), min_df=.2)
X = cv.fit_transform(reviews.Clean_Text)

In [12]:
# view the features / inputs X
X_df = pd.DataFrame(X.toarray(), columns=cv.get_feature_names_out())
X_df.head()

,bag,buy,calorie,chip,eat,flavor,good,great,like,love,popchip,potato,potato chip,salt,snack,taste,try
0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,4,0,3,0,0,1,1,0,0,0,2,0,0,1
2,0,0,0,3,0,0,0,1,0,2,1,1,1,1,0,0,0
3,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0
4,1,0,0,2,1,2,0,1,2,0,0,1,1,0,0,1,0

In [13]:
# view the target / output y
y = reviews.Priority
y.head()

0     Low
1     Low
2     Low
3    High
4     Low
Name: Priority, dtype: str

In [14]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Naive Bias

In [15]:
from sklearn.naive_bayes import MultinomialNB

# Initialize the Naive Bayes classifier
nb = MultinomialNB()

# Train the model
nb.fit(X_train, y_train)

# Make predictions
y_pred_nb = nb.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred_nb))
print(f'Accuracy: {accuracy_score(y_test, y_pred_nb):.2f}')

              precision    recall  f1-score   support

        High       0.60      0.16      0.25        19
         Low       0.85      0.98      0.91        94

    accuracy                           0.84       113
   macro avg       0.73      0.57      0.58       113
weighted avg       0.81      0.84      0.80       113

Accuracy: 0.84

# Neural Network

In [32]:
from sklearn.neural_network import MLPClassifier

# Initialize the MLPClassifer classifier
nn = MLPClassifier(hidden_layer_sizes=(100,), activation='relu', max_iter=2000, random_state=42)

# Train the model
nn.fit(X_train, y_train)

# Make predictions
y_pred_nn = nn.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred_nn))
print(f'Accuracy: {accuracy_score(y_test, y_pred_nn):.2f}')

              precision    recall  f1-score   support

        High       0.47      0.47      0.47        19
         Low       0.89      0.89      0.89        94

    accuracy                           0.82       113
   macro avg       0.68      0.68      0.68       113
weighted avg       0.82      0.82      0.82       113

Accuracy: 0.82

In [36]:
# access the weights (coefs_) and biases (intercepts_)
weights = nn.coefs_  # list of weight matrices
biases = nn.intercepts_  # list of bias vectors

# print out the weight matrices and bias vectors for each layer
for i, (w, b) in enumerate(zip(weights, biases)):
    print(f"Connections {i+1}:")
    print("  Weights:")
    print(w)  # weight matrix
    print("  Biases:")
    print(b)  # bias vector
    print()

Connections 1:
  Weights:
[[ 0.33452236  0.5190567   0.67316117 ... -0.18012695 -0.5896681
  -0.23272953]
 [ 0.01435348  0.22926064 -0.09666122 ... -0.12653305  0.67652654
   0.07746907]
 [ 0.58609961 -0.3190166  -0.66285049 ... -0.9122413   0.53283606
   0.14630577]
 ...
 [-0.19953482 -0.5059111  -0.41900372 ...  0.32415444 -0.42564764
   0.63989398]
 [ 0.19275796 -0.36125576 -1.27080758 ...  0.38005587 -0.38581292
   0.50077378]
 [ 0.10822314 -0.96756866 -0.11554957 ... -1.4234312   0.5384068
  -0.24184118]]
  Biases:
[ 4.91952737e-01 -2.53197106e-01  1.79958927e-01 -7.42023686e-02
 -2.30622902e-01 -3.84517371e-01  1.22879494e-01 -2.93635630e-01
  1.14048624e-01 -4.29548853e-01 -9.73600446e-02 -2.58390131e-01
  1.58130221e-01  5.64754385e-02 -3.73950765e-01  2.01670274e-01
 -2.91177193e-01  1.08322977e-01  5.49482876e-01  2.43765311e-01
 -2.81000883e-01 -2.61297185e-01  4.72519423e-02 -3.02158601e-01
  1.35636762e-01 -3.65753694e-02 -5.91502478e-01  2.11606755e-01
  1.74239876e-01  3.77249520e-01  3.24326163e-01  3.63637928e-03
  4.45331589e-02  1.02393115e-02 -7.70352973e-02  2.03424224e-01
 -9.10474984e-02 -3.14720443e-01 -4.47460151e-02  2.58310495e-01
  3.19943181e-01  5.89628876e-01  8.49541788e-02 -3.93837394e-01
 -1.57226762e-01  9.18996204e-02 -8.27656503e-01 -5.24613270e-01
  1.22018753e-01 -2.44406926e-01  1.61538885e-01 -1.39754200e-01
 -5.02697066e-01 -2.92621077e-02  6.01538152e-01  2.83191910e-01
  6.11441688e-01 -3.37111666e-01 -8.55913718e-02  2.66834031e-01
  3.10627698e-02  1.79961680e-01 -1.59401993e-01 -6.08420339e-02
 -3.64116989e-01 -4.80518514e-02  7.44408821e-02  2.05926237e-01
 -1.68134295e-01 -2.23804776e-01  7.54851456e-04  2.79209374e-01
  3.21772630e-01  1.07970693e-01  1.66929546e-01 -1.73299751e-02
  1.01724412e-01  1.46194812e-01 -6.79239965e-01  2.34591687e-01
 -3.65525648e-01  1.01811615e-01  1.31900300e-01  6.47731144e-02
 -2.79823126e-02  3.06744645e-01  2.28346103e-01  6.02829025e-01
 -5.02653385e-01  7.19694207e-03 -8.47041181e-02  2.24935646e-01
  5.39457728e-02  2.87539895e-01 -7.38722529e-01 -3.28442327e-01
 -1.45333657e-01 -1.38680278e-01 -2.53013760e-01 -3.81061259e-01]

Connections 2:
  Weights:
[[ 1.7409183 ]
 [ 1.1925835 ]
 [-1.40852217]
 [-0.32686969]
 [-0.55254956]
 [ 0.51216865]
 [ 0.56649309]
 [-0.56327716]
 [-0.4662846 ]
 [-1.44781801]
 [ 0.87176592]
 [ 0.70926515]
 [-0.57295611]
 [-0.42088999]
 [-0.84517909]
 [ 0.28359745]
 [-1.07248162]
 [ 0.19101518]
 [ 0.61658171]
 [-1.13718825]
 [-0.81388825]
 [-0.99975925]
 [ 0.22240909]
 [ 1.27301046]
 [ 0.14059618]
 [ 0.50289365]
 [-1.82000506]
 [ 0.27452784]
 [ 0.60842464]
 [-1.00785504]
 [ 1.174146  ]
 [ 0.13911064]
 [ 1.04779864]
 [ 1.4191724 ]
 [ 1.71631492]
 [ 0.80914271]
 [-0.33996585]
 [-0.7617725 ]
 [ 0.81154626]
 [-1.7738009 ]
 [-0.52060376]
 [-0.7904799 ]
 [-1.69056052]
 [ 0.8211475 ]
 [ 1.50739228]
 [-0.63480701]
 [-1.0799148 ]
 [-1.15120296]
 [ 0.13461071]
 [ 0.34702946]
 [-0.56776034]
 [ 0.33965714]
 [ 0.95515826]
 [ 0.3532351 ]
 [ 1.33787116]
 [-0.93394401]
 [ 0.85822227]
 [ 1.78399702]
 [ 0.68247474]
 [ 0.43756201]
 [ 1.28210504]
 [-0.01118998]
 [-0.79927005]
 [ 1.00944181]
 [ 0.85114259]
 [ 1.21000692]
 [-0.6959698 ]
 [-0.67661726]
 [-1.44191068]
 [ 1.39377842]
 [ 1.60481575]
 [-0.83834326]
 [ 0.81798908]
 [ 0.2769628 ]
 [ 0.74040656]
 [ 1.15871717]
 [ 0.34999137]
 [-1.02119607]
 [-0.61084067]
 [ 0.57819841]
 [ 1.41980226]
 [ 0.25867902]
 [ 1.21720396]
 [ 0.95355385]
 [-0.3409626 ]
 [ 0.2152583 ]
 [-1.06358668]
 [-1.99970432]
 [ 0.84403617]
 [ 0.46531421]
 [-1.13553395]
 [-0.6565489 ]
 [ 0.70708292]
 [-1.27309221]
 [-1.53348607]
 [ 0.77554224]
 [ 0.28331241]
 [-1.29754503]
 [-0.9662176 ]
 [ 1.39829065]]
  Biases:
[-0.01598741]