## NLP with Machine Learning

## Sentiment Analysis

In [51]:
import pandas as pd

# create a list of sentences
data = [
    "When life gives you lemons, make lemonade! 🙂",
    "She bought 2 lemons for $1 at Maven Market.",
    "A dozen lemons will make a gallon of lemonade. [AllRecipes]",
    "lemon, lemon, lemons, lemon, lemon, lemons",
    "He's running to the market to get a lemon — there's a great sale today.",
    "iced tea is my favorite",
    "I didn't like the taste of that lemonade at all.",
    "My lemons went bad before I could use them, unfortunately.",
]

# expand the column width to see the full sentences
pd.set_option('display.max_colwidth', None)

# turn it into a dataframe
data_df = pd.DataFrame(data, columns=["sentence"])
data_df.head()

# make a copy of the dataframe
df = data_df.copy()
df.head()

                                                                  sentence
0                             When life gives you lemons, make lemonade! 🙂
1                              She bought 2 lemons for $1 at Maven Market.
2              A dozen lemons will make a gallon of lemonade. [AllRecipes]
3                               lemon, lemon, lemons, lemon, lemon, lemons
4  He's running to the market to get a lemon — there's a great sale today.

In [52]:
phrase = df.sentence[0]
phrase

'When life gives you lemons, make lemonade! 🙂'

In [53]:
## Importing vader for sentiment analysis
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()
sentiment = analyzer.polarity_scores(phrase)
sentiment

{'neg': 0.0, 'neu': 0.75, 'pos': 0.25, 'compound': 0.4587}

In [54]:
sentiment['compound']

0.4587

# Text Classification

## Using import and naive bias to clasify text

In [175]:
# Training model
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [ ]:
from pathlib import Path
# Find the folder where your notebook is located
NOTEBOOK_DIR = Path.cwd()
# If using pathlib, construct the path dynamically
# If the "Data" folder is sitting inside "Course Materials" relative to the notebook:
# file_path = NOTEBOOK_DIR / "Course Materials" / "Data" / "Popchip.xlsx"
data_path = NOTEBOOK_DIR / "Course Materials" / "Data" / "Popchip_Reviews.xlsx"

In [63]:
data_df = pd.read_excel(data_path)
data_df.head(2)

,Id,UserId,Rating,Priority,Title,Text
0,23689,A21SYVGVNG8RAS,5,Low,Yummy snacks!,Popchips are the bomb!! I use the parmesan garlic to scoop up cottage cheese as a healthy alternative to chips and dip. My healthy eating program is saved.
1,23690,AQJYXC0MPRQJL,5,Low,Great chip that is different from the rest,"I like the puffed nature of this chip that makes it more unique in the chip market. I ordered the Salt and Vinegar and absolutely love that flavor, hands down my favorite chip ever. I have tried the cheddar and regular flavors as well. The cheddar is about a 4/5 and the regular is about a 3/5 because I prefer strong flavors and obviously that would not be the case for the regular. The Salt and Vinegar is kind of weak compared to some regular S&V chips, but is quite flavorful and makes you wanting to come back for more."

In [64]:
data_df.shape

(564, 6)

In [65]:
data_df.isna().sum()

Id          0
UserId      0
Rating      0
Priority    0
Title       0
Text        0
dtype: int64

In [66]:
data_df.Priority.value_counts()

Priority
Low     447
High    117
Name: count, dtype: int64

In [67]:
## importing custom functions for text preprocessing
import text_preprocessing as tp

In [90]:
data_df.head(2)

,Id,UserId,Rating,Priority,Title,Text
0,23689,A21SYVGVNG8RAS,5,Low,Yummy snacks!,Popchips are the bomb!! I use the parmesan garlic to scoop up cottage cheese as a healthy alternative to chips and dip. My healthy eating program is saved.
1,23690,AQJYXC0MPRQJL,5,Low,Great chip that is different from the rest,"I like the puffed nature of this chip that makes it more unique in the chip market. I ordered the Salt and Vinegar and absolutely love that flavor, hands down my favorite chip ever. I have tried the cheddar and regular flavors as well. The cheddar is about a 4/5 and the regular is about a 3/5 because I prefer strong flavors and obviously that would not be the case for the regular. The Salt and Vinegar is kind of weak compared to some regular S&V chips, but is quite flavorful and makes you wanting to come back for more."

In [91]:
data_df['Clean_Text'] = tp.lower_replace_special_char(data_df.Text)

In [92]:
data_df.head(2)

,Id,UserId,Rating,Priority,Title,Text,Clean_Text
0,23689,A21SYVGVNG8RAS,5,Low,Yummy snacks!,Popchips are the bomb!! I use the parmesan garlic to scoop up cottage cheese as a healthy alternative to chips and dip. My healthy eating program is saved.,popchips are the bomb i use the parmesan garlic to scoop up cottage cheese as a healthy alternative to chips and dip my healthy eating program is saved
1,23690,AQJYXC0MPRQJL,5,Low,Great chip that is different from the rest,"I like the puffed nature of this chip that makes it more unique in the chip market. I ordered the Salt and Vinegar and absolutely love that flavor, hands down my favorite chip ever. I have tried the cheddar and regular flavors as well. The cheddar is about a 4/5 and the regular is about a 3/5 because I prefer strong flavors and obviously that would not be the case for the regular. The Salt and Vinegar is kind of weak compared to some regular S&V chips, but is quite flavorful and makes you wanting to come back for more.",i like the puffed nature of this chip that makes it more unique in the chip market i ordered the salt and vinegar and absolutely love that flavor hands down my favorite chip ever i have tried the cheddar and regular flavors as well the cheddar is about a 45 and the regular is about a 35 because i prefer strong flavors and obviously that would not be the case for the regular the salt and vinegar is kind of weak compared to some regular sv chips but is quite flavorful and makes you wanting to come back for more

In [93]:
data_df['Clean_Text'] = data_df.Clean_Text.apply(tp.token_lemma_stopw_join)

In [94]:
data_df.head(2)

,Id,UserId,Rating,Priority,Title,Text,Clean_Text
0,23689,A21SYVGVNG8RAS,5,Low,Yummy snacks!,Popchips are the bomb!! I use the parmesan garlic to scoop up cottage cheese as a healthy alternative to chips and dip. My healthy eating program is saved.,popchip bomb use parmesan garlic scoop cottage cheese healthy alternative chip dip healthy eat program save
1,23690,AQJYXC0MPRQJL,5,Low,Great chip that is different from the rest,"I like the puffed nature of this chip that makes it more unique in the chip market. I ordered the Salt and Vinegar and absolutely love that flavor, hands down my favorite chip ever. I have tried the cheddar and regular flavors as well. The cheddar is about a 4/5 and the regular is about a 3/5 because I prefer strong flavors and obviously that would not be the case for the regular. The Salt and Vinegar is kind of weak compared to some regular S&V chips, but is quite flavorful and makes you wanting to come back for more.",like puff nature chip make unique chip market order salt vinegar absolutely love flavor hand favorite chip try cheddar regular flavor cheddar 45 regular 35 prefer strong flavor obviously case regular salt vinegar kind weak compare regular sv chip flavorful make want come

In [151]:
vectorizer = CountVectorizer(stop_words="english", ngram_range=(1,2), min_df=.2)
X = vectorizer.fit_transform(data_df.Clean_Text)
X_df = pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names_out())
X_df

,bag,buy,calorie,chip,eat,flavor,good,great,like,love,popchip,potato,potato chip,salt,snack,taste,try
0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,4,0,3,0,0,1,1,0,0,0,2,0,0,1
2,0,0,0,3,0,0,0,1,0,2,1,1,1,1,0,0,0
3,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0
4,1,0,0,2,1,2,0,1,2,0,0,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,0,0,0,3,3,1,1,5,0,1,1,4,3,0,0,1,0
560,1,0,0,0,0,1,0,1,0,0,1,0,0,0,1,0,1
561,0,0,0,2,0,1,0,2,0,0,0,0,0,0,0,2,0
562,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0
563,0,1,0,2,0,0,1,0,0,0,0,0,0,0,0,0,0

In [152]:
# X_df = data_df.Clean_Text
y = data_df.Priority
y.head()

0     Low
1     Low
2     Low
3    High
4     Low
Name: Priority, dtype: str

In [153]:
# ---------------------------------------------------
# Train-Test Split
# ---------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_df,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
X_train.shape

(451, 17)

In [156]:
# ---------------------------------------------------
# Train
# ---------------------------------------------------
nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)


# ---------------------------------------------------
# TF-IDF + Naive Bayes Pipeline
# ---------------------------------------------------
# nb_model = Pipeline([
#     ("vectorizer", CountVectorizer(
#         lowercase=True,
#         stop_words="english",
#         ngram_range=(1,2),
#         min_df=2
#     )),
#     ("classifier", MultinomialNB())
# ])

MultinomialNB()

In [157]:
# ---------------------------------------------------
# Prediction
# ---------------------------------------------------
y_pred = nb_model.predict(X_test)

In [158]:
# ---------------------------------------------------
# Evaluation
# ---------------------------------------------------
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.7876106194690266

Classification Report
              precision    recall  f1-score   support

        High       0.44      0.17      0.25        23
         Low       0.82      0.94      0.88        90

    accuracy                           0.79       113
   macro avg       0.63      0.56      0.56       113
weighted avg       0.74      0.79      0.75       113


Confusion Matrix
[[ 4 19]
 [ 5 85]]

## Testing prediction on unsen data

In [159]:
# test it out on new reviews
new_reviews = pd.Series([
    "Pop chips are my favorite! I love these chips so much.",
    "Taste bad. I don't like the flavor options or taste.",
    "Solid snack."
])

In [160]:

new_reviews = tp.lower_replace_special_char(new_reviews)

In [162]:
new_clean_reviews = new_reviews.apply(tp.token_lemma_stopw_join)
new_clean_reviews

0               pop chip favorite love chip
1    taste bad not like flavor option taste
2                               solid snack
dtype: str

In [168]:
cv = vectorizer.transform(new_clean_reviews)
new_review_df = pd.DataFrame(cv.toarray(), columns=vectorizer.get_feature_names_out())
new_review_df

,bag,buy,calorie,chip,eat,flavor,good,great,like,love,popchip,potato,potato chip,salt,snack,taste,try
0,0,0,0,2,0,0,0,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,2,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [169]:
nb_model.predict(new_review_df)

array(['Low', 'High', 'Low'], dtype='<U4')

# TF-IDF Vectorizer

In [171]:
tv = TfidfVectorizer(stop_words="english", ngram_range=(1,2), min_df=.2)
Xt = tv.fit_transform(data_df.Clean_Text)
Xt_df = pd.DataFrame(Xt.toarray(),columns=tv.get_feature_names_out())
Xt_df.head()

,bag,buy,calorie,chip,eat,flavor,good,great,like,love,popchip,potato,potato chip,salt,snack,taste,try
0,0.000000,0.000000,0.0,0.392603,0.656435,0.000000,0.0,0.000000,0.000000,0.000000,0.644170,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
1,0.000000,0.000000,0.0,0.561185,0.000000,0.537701,0.0,0.000000,0.195524,0.213766,0.000000,0.000000,0.000000,0.513094,0.0,0.000000,0.220814
2,0.000000,0.000000,0.0,0.517908,0.000000,0.000000,0.0,0.295101,0.000000,0.526082,0.283255,0.277355,0.333330,0.315684,0.0,0.000000,0.000000
3,0.000000,0.690063,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.512918,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.510616,0.000000
4,0.252776,0.000000,0.0,0.340747,0.284866,0.435318,0.0,0.291234,0.474884,0.000000,0.000000,0.273721,0.328962,0.000000,0.0,0.236376,0.000000

In [172]:
y = data_df.Priority
y.head()

0     Low
1     Low
2     Low
3    High
4     Low
Name: Priority, dtype: str

In [173]:
# ---------------------------------------------------
# Train-Test Split
# ---------------------------------------------------
Xt_train, Xt_test, yt_train, yt_test = train_test_split(
    Xt_df,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
Xt_train.shape

(451, 17)

In [176]:
model_lr = LogisticRegression()
model_lr.fit(Xt_train, yt_train)

LogisticRegression()

In [178]:
# ---------------------------------------------------
# Prediction
# ---------------------------------------------------
yt_pred = model_lr.predict(Xt_test)

# ---------------------------------------------------
# Evaluation
# ---------------------------------------------------
print("Accuracy:", accuracy_score(yt_test, yt_pred))

print("\nClassification Report")
print(classification_report(yt_test, yt_pred))

print("\nConfusion Matrix")
print(confusion_matrix(yt_test, yt_pred))

Accuracy: 0.7964601769911505

Classification Report
              precision    recall  f1-score   support

        High       0.50      0.09      0.15        23
         Low       0.81      0.98      0.88        90

    accuracy                           0.80       113
   macro avg       0.65      0.53      0.52       113
weighted avg       0.74      0.80      0.73       113


Confusion Matrix
[[ 2 21]
 [ 2 88]]

In [179]:
data_df.head(2)

,Id,UserId,Rating,Priority,Title,Text,Clean_Text
0,23689,A21SYVGVNG8RAS,5,Low,Yummy snacks!,Popchips are the bomb!! I use the parmesan garlic to scoop up cottage cheese as a healthy alternative to chips and dip. My healthy eating program is saved.,popchip bomb use parmesan garlic scoop cottage cheese healthy alternative chip dip healthy eat program save
1,23690,AQJYXC0MPRQJL,5,Low,Great chip that is different from the rest,"I like the puffed nature of this chip that makes it more unique in the chip market. I ordered the Salt and Vinegar and absolutely love that flavor, hands down my favorite chip ever. I have tried the cheddar and regular flavors as well. The cheddar is about a 4/5 and the regular is about a 3/5 because I prefer strong flavors and obviously that would not be the case for the regular. The Salt and Vinegar is kind of weak compared to some regular S&V chips, but is quite flavorful and makes you wanting to come back for more.",like puff nature chip make unique chip market order salt vinegar absolutely love flavor hand favorite chip try cheddar regular flavor cheddar 45 regular 35 prefer strong flavor obviously case regular salt vinegar kind weak compare regular sv chip flavorful make want come

In [186]:
data_df['predictions_nb'] = nb_model.predict_proba(X_df)[:, 0]
data_df['predictions_lr'] = model_lr.predict_proba(Xt_df)[:, 0]
data_df.sort_values('predictions_nb', ascending=False).head(2)

,Id,UserId,Rating,Priority,Title,Text,Clean_Text,predictions_nb,predictions_lr
550,24239,A2ZKS33N6Y3EPC,3,High,"Taste more like ""Tomato and Basil"" than ""Chili and Lime""","NOTE: This review is for the Chili and Lime Flavor Popchip. Amazon had a separate page for it but then merged the product and its reviews into one.<br /><br />It's hard to objectively review food since everyone's palate and tastes are different. So what I can say about this particular Popchip flavor that should be useful for most folks out there is that it doesn't really taste like Chili and Lime you're ""probably"" expecting. The Chili and Lime most folks probably are expecting if they grew up on Frito Lay products is very sharp and sweet (and of course artificial) - but it's what we liked if we ate more than a bag.<br /><br />The best way I can describe this flavor is that it has a ""tomato"" like taste to it with a somewhat tangy sour note that is suppose to be the lime component. Together they turn into an odd combination that registers other flavors in your mind than Chili and Lime - at least it did to me and others who tasted it with me. If you eat the skin of a green bell pepper, you can kind of get at what Popchips were trying to do with the Chili taste on this version, but I have no idea how some sour salt can be akin to lime. For myself personally, I thought it tasted like ""Tomato and Basil"" you would find on Pita chip flavors and baked snacks.<br /><br />Whether or not you agree with my above description of the flavor, I would highly suggest you try to get this in a sample pack and try it out first. BBQ + Salt & Vinegar Popchips are still my staples for now.",note review chili lime flavor popchip amazon separate page merge product review onebr br hard objectively review food everyone palate taste different particular popchip flavor useful folk not taste like chili lime probably expect chili lime folk probably expect grow frito lay product sharp sweet course artificial like eat bagbr br good way describe flavor tomato like taste somewhat tangy sour note suppose lime component turn odd combination register flavor mind chili lime taste eat skin green bell pepper kind popchip try chili taste version idea sour salt akin lime personally think taste like tomato basil find pita chip flavor bake snacksbr br agree description flavor highly suggest try sample pack try bbq salt vinegar popchip staple,0.995997,0.520013
96,23785,AE5AHEH3NLPBZ,3,High,Tastes Like Celery,"I really like pop chips, but this flavor isn't the best. I was expecting these to taste like chili peppers and lime (Spicy, Sweet, and Tart), but instead of going for a chili pepper taste, they went for a chili the food taste. This wouldn't be so bad, except they taste overwhelmingly of tomato and celery. The reason they didn't call them Tomato and Celery Chips is because it is sounds gross and no one would buy that, and unfortunately it tastes like it sounds.",like pop chip flavor not good expect taste like chili pepper lime spicy sweet tart instead go chili pepper taste go chili food taste not bad taste overwhelmingly tomato celery reason not tomato celery chip sound gross buy unfortunately taste like sound,0.934848,0.549457

In [188]:
print(nb_model.classes_)
print(model_lr.classes_)

['High' 'Low']
['High' 'Low']

# NMF Topic Modelling

In [189]:
data_df.head(2)

,Id,UserId,Rating,Priority,Title,Text,Clean_Text,predictions_nb,predictions_lr
0,23689,A21SYVGVNG8RAS,5,Low,Yummy snacks!,Popchips are the bomb!! I use the parmesan garlic to scoop up cottage cheese as a healthy alternative to chips and dip. My healthy eating program is saved.,popchip bomb use parmesan garlic scoop cottage cheese healthy alternative chip dip healthy eat program save,0.199193,0.218074
1,23690,AQJYXC0MPRQJL,5,Low,Great chip that is different from the rest,"I like the puffed nature of this chip that makes it more unique in the chip market. I ordered the Salt and Vinegar and absolutely love that flavor, hands down my favorite chip ever. I have tried the cheddar and regular flavors as well. The cheddar is about a 4/5 and the regular is about a 3/5 because I prefer strong flavors and obviously that would not be the case for the regular. The Salt and Vinegar is kind of weak compared to some regular S&V chips, but is quite flavorful and makes you wanting to come back for more.",like puff nature chip make unique chip market order salt vinegar absolutely love flavor hand favorite chip try cheddar regular flavor cheddar 45 regular 35 prefer strong flavor obviously case regular salt vinegar kind weak compare regular sv chip flavorful make want come,0.263978,0.234875

In [199]:
tfidf = TfidfVectorizer(stop_words="english", min_df=0.05, max_df=.2)
Xt2 = tfidf.fit_transform(data_df.Clean_Text)
Xt2_df = pd.DataFrame(Xt2.toarray(),columns=tfidf.get_feature_names_out())
Xt2_df

,100,alternative,amazon,bad,bake,baked,bbq,big,bit,box,...,thing,think,time,variety,ve,vinegar,want,way,weight,work
0,0.0,0.465515,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.348295,0.193511,0.000000,0.000000,0.000000
2,0.0,0.000000,0.354088,0.000000,0.0,0.000000,0.000000,0.428869,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.354475,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,0.0,0.324462,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.299888,0.0,0.000000,0.000000,0.000000,0.337388,0.657147,0.000000
560,0.0,0.000000,0.190702,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.197896,0.000000,0.208227,0.000000,0.000000,0.247474
561,0.0,0.378621,0.000000,0.380993,0.0,0.396437,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
562,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.543142,0.000000,0.000000,0.000000,0.000000,0.000000
563,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [198]:
data_df.shape

(564, 9)

In [204]:
from sklearn.decomposition import NMF

nmf = NMF(n_components=2)
W = nmf.fit_transform(Xt2_df) # Documnets-Topics
H = nmf.components_ # Topics-Terms

In [206]:
H.shape

(2, 81)

In [209]:
# function to display the top terms for each topic
def display_topics(H, num_words=10):
    for topic_num, topic_array in enumerate(H):
        top_features = topic_array.argsort()[::-1][:num_words]
        top_words = [tfidf.get_feature_names_out()[i] for i in top_features]
        print("Topic", topic_num+1, ":", ', '.join(top_words))

In [210]:
display_topics(H)

Topic 1 : br, bbq, order, regular, vinegar, favorite, pop, healthy, fat, amazon
Topic 2 : sweet, salty, br, healthy, rice, light, texture, fat, think, little